export enum COUNTRIES_ACTION_TYPES {
  FETCH_COUNTRIES_START = "countries/FETCH_COUNTRIES_START",
  FETCH_COUNTRIES_SUCCESS = "countries/FETCH_COUNTRIES_SUCCESS",
  FETCH_COUNTRIES_FAILED = "countries/FETCH_COUNTRIES_FAILED",
}
